steps:
# Build war file
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
# Build the container image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/petclinic-springboot:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/petclinic-springboot:latest", "--build-arg=WAR_FILE=target/petclinic.war", "."]
# Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
    [
      "beta", "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "petclinic-delivery",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "IMAGE_NAME=gcr.io/$PROJECT_ID/petclinic-springboot:${COMMIT_SHA}"
    ]
images:
  - 'gcr.io/$PROJECT_ID/petclinic-springboot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/petclinic-springboot:latest'
