steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tomcat-petclinic:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/tomcat-petclinic:latest", "--build-arg=WAR_FILE=target/petclinic.war", "."]
images:
  - 'gcr.io/$PROJECT_ID/tomcat-petclinic:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/tomcat-petclinic:latest'
